window.WC_TEAMS = {
  "teams": [
    {
      "code": "MEX",
      "name_en": "Mexico",
      "name_zh": "墨西哥",
      "elo": 1875,
      "host": true,
      "open": 1.0,
      "group": "A",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.033,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "RSA",
      "name_en": "South Africa",
      "name_zh": "南非",
      "elo": 1517,
      "host": false,
      "open": 1.0,
      "group": "A",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.833,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "KOR",
      "name_en": "South Korea",
      "name_zh": "韩国",
      "elo": 1758,
      "host": false,
      "open": 1.0,
      "group": "A",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.048,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "CZE",
      "name_en": "Czechia",
      "name_zh": "捷克",
      "elo": 1740,
      "host": false,
      "open": 1.0,
      "group": "A",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.933,
        "defense_factor": 0.769,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "CAN",
      "name_en": "Canada",
      "name_zh": "加拿大",
      "elo": 1788,
      "host": true,
      "open": 1.0,
      "group": "B",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.067,
        "defense_factor": 0.909,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "BIH",
      "name_en": "Bosnia and Herzegovina",
      "name_zh": "波黑",
      "elo": 1595,
      "host": false,
      "open": 1.0,
      "group": "B",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.75,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "QAT",
      "name_en": "Qatar",
      "name_zh": "卡塔尔",
      "elo": 1421,
      "host": false,
      "open": 1.0,
      "group": "B",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.048,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "SUI",
      "name_en": "Switzerland",
      "name_zh": "瑞士",
      "elo": 1891,
      "host": false,
      "open": 1.0,
      "group": "B",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.072,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "BRA",
      "name_en": "Brazil",
      "name_zh": "巴西",
      "elo": 1991,
      "host": false,
      "open": 1.0,
      "group": "C",
      "boost": {
        "form_factor": 1.3,
        "attack_factor": 1.25,
        "defense_factor": 1.35,
        "style_open": 1.02,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "MAR",
      "name_en": "Morocco",
      "name_zh": "摩洛哥",
      "elo": 1827,
      "host": false,
      "open": 1.0,
      "group": "C",
      "boost": {
        "form_factor": 1.2,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.987,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.21,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "HAI",
      "name_en": "Haiti",
      "name_zh": "海地",
      "elo": 1548,
      "host": false,
      "open": 1.0,
      "group": "C",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.75,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "SCO",
      "name_en": "Scotland",
      "name_zh": "苏格兰",
      "elo": 1782,
      "host": false,
      "open": 1.0,
      "group": "C",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.867,
        "defense_factor": 0.833,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "USA",
      "name_en": "United States",
      "name_zh": "美国",
      "elo": 1726,
      "host": true,
      "open": 1.0,
      "group": "D",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.117,
        "giant_killer": 0.0,
        "strong_but_weak": 0.048,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "PAR",
      "name_en": "Paraguay",
      "name_zh": "巴拉圭",
      "elo": 1834,
      "host": false,
      "open": 1.0,
      "group": "D",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.818,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "AUS",
      "name_en": "Australia",
      "name_zh": "澳大利亚",
      "elo": 1777,
      "host": false,
      "open": 1.0,
      "group": "D",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.851,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "TUR",
      "name_en": "Türkiye",
      "name_zh": "土耳其",
      "elo": 1911,
      "host": false,
      "open": 1.0,
      "group": "D",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.117,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "GER",
      "name_en": "Germany",
      "name_zh": "德国",
      "elo": 1932,
      "host": false,
      "open": 1.0,
      "group": "E",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.052,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "CUW",
      "name_en": "Curaçao",
      "name_zh": "库拉索",
      "elo": 1434,
      "host": false,
      "open": 1.0,
      "group": "E",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "CIV",
      "name_en": "Ivory Coast",
      "name_zh": "科特迪瓦",
      "elo": 1695,
      "host": false,
      "open": 1.0,
      "group": "E",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.21,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "ECU",
      "name_en": "Ecuador",
      "name_zh": "厄瓜多尔",
      "elo": 1938,
      "host": false,
      "open": 1.0,
      "group": "E",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "NED",
      "name_en": "Netherlands",
      "name_zh": "荷兰",
      "elo": 1948,
      "host": false,
      "open": 1.0,
      "group": "F",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.072,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "JPN",
      "name_en": "Japan",
      "name_zh": "日本",
      "elo": 1906,
      "host": false,
      "open": 1.0,
      "group": "F",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.149,
        "giant_killer": 0.18,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "SWE",
      "name_en": "Sweden",
      "name_zh": "瑞典",
      "elo": 1712,
      "host": false,
      "open": 1.0,
      "group": "F",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "TUN",
      "name_en": "Tunisia",
      "name_zh": "突尼斯",
      "elo": 1628,
      "host": false,
      "open": 1.0,
      "group": "F",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "BEL",
      "name_en": "Belgium",
      "name_zh": "比利时",
      "elo": 1894,
      "host": false,
      "open": 1.0,
      "group": "G",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.117,
        "giant_killer": 0.0,
        "strong_but_weak": 0.048,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "EGY",
      "name_en": "Egypt",
      "name_zh": "埃及",
      "elo": 1696,
      "host": false,
      "open": 1.0,
      "group": "G",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.21,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "IRN",
      "name_en": "Iran",
      "name_zh": "伊朗",
      "elo": 1772,
      "host": false,
      "open": 1.0,
      "group": "G",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.948,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "NZL",
      "name_en": "New Zealand",
      "name_zh": "新西兰",
      "elo": 1562,
      "host": false,
      "open": 1.0,
      "group": "G",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "ESP",
      "name_en": "Spain",
      "name_zh": "西班牙",
      "elo": 2157,
      "host": false,
      "open": 1.0,
      "group": "H",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.2,
        "defense_factor": 1.111,
        "style_open": 1.033,
        "giant_killer": 0.0,
        "strong_but_weak": 0.072,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "CPV",
      "name_en": "Cape Verde",
      "name_zh": "佛得角",
      "elo": 1578,
      "host": false,
      "open": 1.0,
      "group": "H",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.769,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "KSA",
      "name_en": "Saudi Arabia",
      "name_zh": "沙特阿拉伯",
      "elo": 1576,
      "host": false,
      "open": 1.0,
      "group": "H",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.87,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "URU",
      "name_en": "Uruguay",
      "name_zh": "乌拉圭",
      "elo": 1892,
      "host": false,
      "open": 1.0,
      "group": "H",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.162,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "FRA",
      "name_en": "France",
      "name_zh": "法国",
      "elo": 2063,
      "host": false,
      "open": 1.0,
      "group": "I",
      "boost": {
        "form_factor": 1.3,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.033,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "SEN",
      "name_en": "Senegal",
      "name_zh": "塞内加尔",
      "elo": 1860,
      "host": false,
      "open": 1.0,
      "group": "I",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.117,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "IRQ",
      "name_en": "Iraq",
      "name_zh": "伊拉克",
      "elo": 1607,
      "host": false,
      "open": 1.0,
      "group": "I",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.818,
        "giant_killer": 0.06,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "NOR",
      "name_en": "Norway",
      "name_zh": "挪威",
      "elo": 1914,
      "host": false,
      "open": 1.0,
      "group": "I",
      "boost": {
        "form_factor": 1.2,
        "attack_factor": 1.25,
        "defense_factor": 1.111,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "ARG",
      "name_en": "Argentina",
      "name_zh": "阿根廷",
      "elo": 2115,
      "host": false,
      "open": 1.0,
      "group": "J",
      "boost": {
        "form_factor": 1.3,
        "attack_factor": 1.25,
        "defense_factor": 1.25,
        "style_open": 1.033,
        "giant_killer": 0.0,
        "strong_but_weak": 0.048,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "ALG",
      "name_en": "Algeria",
      "name_zh": "阿尔及利亚",
      "elo": 1772,
      "host": false,
      "open": 1.0,
      "group": "J",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.09,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "AUT",
      "name_en": "Austria",
      "name_zh": "奥地利",
      "elo": 1830,
      "host": false,
      "open": 1.0,
      "group": "J",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.133,
        "defense_factor": 1.0,
        "style_open": 0.948,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "JOR",
      "name_en": "Jordan",
      "name_zh": "约旦",
      "elo": 1680,
      "host": false,
      "open": 1.0,
      "group": "J",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.833,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "POR",
      "name_en": "Portugal",
      "name_zh": "葡萄牙",
      "elo": 1989,
      "host": false,
      "open": 1.0,
      "group": "K",
      "boost": {
        "form_factor": 1.3,
        "attack_factor": 1.25,
        "defense_factor": 1.0,
        "style_open": 1.033,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "COD",
      "name_en": "DR Congo",
      "name_zh": "刚果(金)",
      "elo": 1652,
      "host": false,
      "open": 1.0,
      "group": "K",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.933,
        "defense_factor": 0.769,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "UZB",
      "name_en": "Uzbekistan",
      "name_zh": "乌兹别克斯坦",
      "elo": 1714,
      "host": false,
      "open": 1.0,
      "group": "K",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.769,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "COL",
      "name_en": "Colombia",
      "name_zh": "哥伦比亚",
      "elo": 1982,
      "host": false,
      "open": 1.0,
      "group": "K",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "ENG",
      "name_en": "England",
      "name_zh": "英格兰",
      "elo": 2024,
      "host": false,
      "open": 1.0,
      "group": "L",
      "boost": {
        "form_factor": 1.2,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.987,
        "giant_killer": 0.0,
        "strong_but_weak": 0.048,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "CRO",
      "name_en": "Croatia",
      "name_zh": "克罗地亚",
      "elo": 1912,
      "host": false,
      "open": 1.0,
      "group": "L",
      "boost": {
        "form_factor": 1.0,
        "attack_factor": 1.0,
        "defense_factor": 1.0,
        "style_open": 0.902,
        "giant_killer": 0.0,
        "strong_but_weak": 0.072,
        "defensive_strength": 1.175,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "GHA",
      "name_en": "Ghana",
      "name_zh": "加纳",
      "elo": 1510,
      "host": false,
      "open": 1.0,
      "group": "L",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.867,
        "defense_factor": 0.833,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    },
    {
      "code": "PAN",
      "name_en": "Panama",
      "name_zh": "巴拿马",
      "elo": 1730,
      "host": false,
      "open": 1.0,
      "group": "L",
      "boost": {
        "form_factor": 0.8,
        "attack_factor": 0.85,
        "defense_factor": 0.75,
        "style_open": 1.0,
        "giant_killer": 0.0,
        "strong_but_weak": 0.0,
        "defensive_strength": 1.0,
        "book_draw_bias": 0.0,
        "book_upset": 0.0,
        "book_mentions": 0
      }
    }
  ]
};
window.WC_CALIBRATION = {
  "book_home_bias": 0.5,
  "book_upset_emphasis": 0.5,
  "book_draw_emphasis": 0.5,
  "book_strong_team_caution": 0.5,
  "book_total_goals_calibration": 1.018
};
